# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    # image: devops-for-programmers-project-lvl1
    build:
      context: .
    #   # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    #   # Команда, которая будет выполнена после старта сервиса
    command: "bash -c 'sleep 3 && npm start'"
    ports: # Проброс портов
      - "8080:8080"
    # # Перечисляем тома (volumes)
    # # Они будут подключены к файловой системе сервиса
    # # Например, все что находится в . мы увидим в директории /app
    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      - "./app:/app/"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
#       - caddy_data:/data
#       - caddy_config:/config
# volumes:
#   caddy_data:
#   caddy_config: