# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: localhost

  app: # Имя сервиса
    image: generalitalics/devops-for-programmers-project-lvl1:latest
    build:
    #   # Контекст для сборки образа,
    #   # в данном случае, текущая директория
      context: .
    #   # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile.production
    #   # Команда, которая будет выполнена после старта сервиса
    command: npm test
    # ports: # Проброс портов
    #   - "3000:8000"
    # # Перечисляем тома (volumes)
    # # Они будут подключены к файловой системе сервиса
    # # Например, все что находится в . мы увидим в директории /app
    depends_on:
      - db