# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    # image: devops-for-programmers-project-lvl1
    build:
    #   # Контекст для сборки образа,
    #   # в данном случае, текущая директория
      # context: ./app
    #   # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    #   # Команда, которая будет выполнена после старта сервиса
    command: make test
    # ports: # Проброс портов
    #   - "3000:8000"
    # # Перечисляем тома (volumes)
    # # Они будут подключены к файловой системе сервиса
    # # Например, все что находится в . мы увидим в директории /app
    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      - "./app:/app"
